"""
action_agent.py
Agent 3 of 3 in the AI-Q pipeline.
Creates GitHub issues, branches, commits, and PRs
from the AnalysisReport produced by the Research Agent.
"""

import os
import re
from dotenv import load_dotenv
from github import Github, GithubException
from agents.shared_models import (
    AnalysisReport,
    GitHubArtifact,
    GitHubArtifacts,
)

load_dotenv()

gh = Github(os.getenv("GITHUB_TOKEN"))
repo = gh.get_repo(os.getenv("GITHUB_REPO"))

def _slugify(text: str, max_len: int = 40) -> str:
    """Convert issue title to a branch-safe slug."""
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug[:max_len]

def _build_issue_body(issue) -> str:
    """Format a GitHub issue body."""
    return (
        "## 🔍 Issue Detected by Nemotron Analysis\n\n"
        f"**File:** `{issue.file_path}`\n"
        f"**Lines:** {issue.line_start} – {issue.line_end}\n"
        f"**Severity:** {issue.severity.upper()} (score: {issue.severity_score}/10)\n"
        f"**Category:** {issue.category}\n\n"
        "### Description\n"
        f"{issue.description}\n\n"
        "### Problematic Code\n"
        f"```\n{issue.code_snippet}\n```\n\n"
        "### Impact\n"
        f"{issue.impact}\n\n"
        "### Suggested Fix\n"
        f"{issue.fix_suggestion}\n\n"
        "*This issue was automatically generated by the AI-Q pipeline using Nemotron-Nano-9b-v2.*\n"
    )

def _build_pr_body(issue, github_issue_number: int) -> str:
    """Format a Pull Request body."""
    return (
        "## Summary\n\n"
        "This PR addresses the issue identified by Nemotron analysis.\n\n"
        f"**What was wrong:** {issue.description}\n"
        f"**What was changed:** Applied the fix suggestion to `{issue.file_path}` "
        f"at lines {issue.line_start}–{issue.line_end}.\n"
        f"**Why this fix works:** {issue.fix_suggestion}\n"
        "**Assumptions:** Fix applied as suggested by Nemotron-Nano-9b-v2. "
        "Manual review recommended before merging.\n\n"
        f"Closes #{github_issue_number}\n\n"
        "*Generated by the AI-Q agentic pipeline.*\n"
    )

def _apply_fix_to_branch(issue, branch_name: str) -> bool:
    """
    Apply the fix suggestion to the file on the branch.
    Returns True if the fix is applied successfully.
    """
    try:
        contents = repo.get_contents(issue.file_path, ref=branch_name)
        current_code = contents.decoded_content.decode("utf-8")
        if issue.code_snippet and issue.code_snippet in current_code:
            fixed_code = current_code.replace(issue.code_snippet, issue.fix_suggestion, 1)
            repo.update_file(
                path=issue.file_path,
                message=f"Fix: {issue.title} (AI-Q automated fix)",
                content=fixed_code,
                sha=contents.sha,
                branch=branch_name,
            )
            return True
        print(f"  [Action] WARNING: code_snippet not found in {issue.file_path}. Skipping update.")
        return False
    except GithubException as e:
        print(f"  [Action] ERROR applying fix: {e}")
        return False

def run(report: AnalysisReport) -> GitHubArtifacts:
    """
    Entry point for the Action Agent.
    Creates GitHub issues, branches, and Pull Requests for each issue in the report.
    """
    artifacts = []
    default_branch = repo.default_branch
    for issue in report.issues:
        print(f"  [Action] Processing: {issue.title} (score={issue.severity_score})")
        labels = []
        for label_name in [issue.category, issue.severity]:
            try:
                labels.append(repo.get_label(label_name))
            except GithubException:
                try:
                    labels.append(repo.create_label(label_name, "ee0701"))
                except GithubException:
                    pass
        gh_issue = repo.create_issue(
            title=f"[NEMOTRON] {issue.title}",
            body=_build_issue_body(issue),
            labels=labels,
        )
        print(f"  [Action] Created issue #{gh_issue.number}: {gh_issue.html_url}")
        slug = _slugify(issue.title)
        branch_name = f"fix/{gh_issue.number}-{slug}"
        source_sha = repo.get_branch(default_branch).commit.sha
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=source_sha)
        print(f"  [Action] Created branch: {branch_name}")
        fix_applied = _apply_fix_to_branch(issue, branch_name)
        pr_title = f"Fix: {issue.title}"
        pr = repo.create_pull(
            title=pr_title,
            body=_build_pr_body(issue, gh_issue.number),
            head=branch_name,
            base=default_branch,
        )
        print(f"  [Action] Created PR #{pr.number}: {pr.html_url}")
        artifacts.append(
            GitHubArtifact(
                issue_number=gh_issue.number,
                issue_url=gh_issue.html_url,
                branch_name=branch_name,
                pr_number=pr.number,
                pr_url=pr.html_url,
                issue_title=issue.title,
            )
        )
    return GitHubArtifacts(
        run_id=report.run_id,
        artifacts=artifacts,
        total_issues_created=len(artifacts),
        total_prs_created=len(artifacts),
    )