"""
GitHub Service - Integration with GitHub API for automated issue and PR analysis

Provides functionality for:
- Issue analysis and auto-labeling
- Pull request review with AI insights
- Auto-fix PR creation with AI-generated code
- Integration with MCP server for AI analysis
"""

import os
import httpx
import logging
import re
import base64
from typing import Dict, Any, Optional, List
from datetime import datetime

logger = logging.getLogger(__name__)


class GitHubService:
    """Service for GitHub API integration with AI-powered analysis"""
    
    def __init__(self):
        """Initialize GitHub service with configuration from environment"""
        self.github_token = os.getenv("GITHUB_TOKEN")
        self.github_repo = os.getenv("GITHUB_REPO")  # Format: "owner/repo"
        self.mcp_server_url = os.getenv("MCP_SERVER_URL", "http://localhost:8000")
        
        if not self.github_token:
            logger.warning("GITHUB_TOKEN not set - GitHub integration will be disabled")
        
        if not self.github_repo:
            logger.warning("GITHUB_REPO not set - GitHub integration will be disabled")
        
        self.github_api_base = "https://api.github.com"
        self.github_api_version = "2022-11-28"
    
    def _get_github_headers(self) -> Dict[str, str]:
        """Get headers for GitHub API requests"""
        return {
            "Authorization": f"Bearer {self.github_token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": self.github_api_version
        }
    
    # ========================================
    # Main Workflow Methods
    # ========================================
    
    async def analyze_and_label_issue(self, issue_number: int) -> Dict[str, Any]:
        """
        Main workflow: Analyze issue with AI and auto-label.
        
        Steps:
        1. Fetch issue from GitHub API
        2. Call MCP /analyze endpoint for AI analysis
        3. Parse analysis for issue type, priority, suggested labels
        4. Add labels to the issue via GitHub API
        5. Post AI analysis as comment on the issue
        
        Args:
            issue_number: The issue number to analyze
            
        Returns:
            Dict with success status, labels added, and comment URL
        """
        try:
            logger.info(f"Starting analysis for issue #{issue_number}")
            
            # Step 1: Fetch issue details
            issue = await self._get_issue(issue_number)
            if not issue:
                return {
                    "success": False,
                    "error": f"Issue #{issue_number} not found"
                }
            
            # Step 2: Analyze issue with AI
            analysis = await self._analyze_issue_with_ai(
                title=issue["title"],
                body=issue.get("body", "")
            )
            
            if not analysis:
                return {
                    "success": False,
                    "error": "AI analysis failed"
                }
            
            # Step 3: Parse analysis for labels
            suggested_labels = self._parse_labels_from_analysis(analysis)
            
            # Step 4: Add labels to issue
            if suggested_labels:
                await self._add_labels(issue_number, suggested_labels)
                logger.info(f"Added labels to issue #{issue_number}: {suggested_labels}")
            
            # Step 5: Post AI analysis as comment
            comment_body = f"""## 🤖 AI Analysis

{analysis}

---
*Generated by Zava AI Portal using Azure OpenAI*
"""
            comment_url = await self._create_comment(issue_number, comment_body)
            
            logger.info(f"Successfully analyzed issue #{issue_number}")
            return {
                "success": True,
                "issue_number": issue_number,
                "labels_added": suggested_labels,
                "comment_url": comment_url,
                "analysis": analysis
            }
            
        except Exception as e:
            logger.error(f"Error analyzing issue #{issue_number}: {str(e)}")
            return {
                "success": False,
                "error": str(e)
            }
    
    async def review_pull_request(self, pr_number: int) -> Dict[str, Any]:
        """
        Main workflow: Review PR with AI insights.
        
        Steps:
        1. Fetch PR details and changed files from GitHub API
        2. Call MCP /analyze endpoint for code review
        3. Parse review for security, quality, performance issues
        4. Post review comment on PR
        
        Args:
            pr_number: The PR number to review
            
        Returns:
            Dict with success status, review summary, and comment URL
        """
        try:
            logger.info(f"Starting review for PR #{pr_number}")
            
            # Step 1: Fetch PR details
            pr = await self._get_pr(pr_number)
            if not pr:
                return {
                    "success": False,
                    "error": f"PR #{pr_number} not found"
                }
            
            # Get changed files
            files = await self._get_pr_files(pr_number)
            
            # Step 2: Review PR with AI
            review = await self._review_pr_with_ai(
                title=pr["title"],
                description=pr.get("body", ""),
                files=files
            )
            
            if not review:
                return {
                    "success": False,
                    "error": "AI review failed"
                }
            
            # Step 3: Post review comment
            review_body = f"""## 🤖 AI Code Review

{review}

---
*Generated by Zava AI Portal using Azure OpenAI*
"""
            comment_url = await self._create_pr_review_comment(pr_number, review_body)
            
            logger.info(f"Successfully reviewed PR #{pr_number}")
            return {
                "success": True,
                "pr_number": pr_number,
                "comment_url": comment_url,
                "review": review
            }
            
        except Exception as e:
            logger.error(f"Error reviewing PR #{pr_number}: {str(e)}")
            return {
                "success": False,
                "error": str(e)
            }
    
    # ========================================
    # Private Helper Methods - GitHub API
    # ========================================
    
    async def _get_issue(self, issue_number: int) -> Optional[Dict[str, Any]]:
        """Fetch issue details from GitHub API"""
        try:
            url = f"{self.github_api_base}/repos/{self.github_repo}/issues/{issue_number}"
            
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.get(url, headers=self._get_github_headers())
                response.raise_for_status()
                
                issue = response.json()
                logger.info(f"Fetched issue #{issue_number}: {issue['title']}")
                return issue
                
        except httpx.HTTPStatusError as e:
            logger.error(f"GitHub API error fetching issue #{issue_number}: {e.response.status_code}")
            return None
        except Exception as e:
            logger.error(f"Error fetching issue #{issue_number}: {str(e)}")
            return None
    
    async def _get_pr(self, pr_number: int) -> Optional[Dict[str, Any]]:
        """Fetch PR details from GitHub API"""
        try:
            url = f"{self.github_api_base}/repos/{self.github_repo}/pulls/{pr_number}"
            
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.get(url, headers=self._get_github_headers())
                response.raise_for_status()
                
                pr = response.json()
                logger.info(f"Fetched PR #{pr_number}: {pr['title']}")
                return pr
                
        except httpx.HTTPStatusError as e:
            logger.error(f"GitHub API error fetching PR #{pr_number}: {e.response.status_code}")
            return None
        except Exception as e:
            logger.error(f"Error fetching PR #{pr_number}: {str(e)}")
            return None
    
    async def _get_pr_files(self, pr_number: int) -> List[Dict[str, Any]]:
        """Get changed files in a PR from GitHub API"""
        try:
            url = f"{self.github_api_base}/repos/{self.github_repo}/pulls/{pr_number}/files"
            
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.get(url, headers=self._get_github_headers())
                response.raise_for_status()
                
                files = response.json()
                logger.info(f"Fetched {len(files)} changed files for PR #{pr_number}")
                return files
                
        except httpx.HTTPStatusError as e:
            logger.error(f"GitHub API error fetching PR files #{pr_number}: {e.response.status_code}")
            return []
        except Exception as e:
            logger.error(f"Error fetching PR files #{pr_number}: {str(e)}")
            return []
    
    async def _add_labels(self, issue_number: int, labels: List[str]) -> bool:
        """Add labels to an issue via GitHub API"""
        try:
            url = f"{self.github_api_base}/repos/{self.github_repo}/issues/{issue_number}/labels"
            
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.post(
                    url,
                    headers=self._get_github_headers(),
                    json={"labels": labels}
                )
                response.raise_for_status()
                
                logger.info(f"Added labels to issue #{issue_number}: {labels}")
                return True
                
        except httpx.HTTPStatusError as e:
            logger.error(f"GitHub API error adding labels to issue #{issue_number}: {e.response.status_code}")
            return False
        except Exception as e:
            logger.error(f"Error adding labels to issue #{issue_number}: {str(e)}")
            return False
    
    async def _create_comment(self, issue_number: int, body: str) -> Optional[str]:
        """Post a comment on an issue via GitHub API"""
        try:
            url = f"{self.github_api_base}/repos/{self.github_repo}/issues/{issue_number}/comments"
            
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.post(
                    url,
                    headers=self._get_github_headers(),
                    json={"body": body}
                )
                response.raise_for_status()
                
                comment = response.json()
                comment_url = comment.get("html_url")
                logger.info(f"Posted comment on issue #{issue_number}: {comment_url}")
                return comment_url
                
        except httpx.HTTPStatusError as e:
            logger.error(f"GitHub API error creating comment on issue #{issue_number}: {e.response.status_code}")
            return None
        except Exception as e:
            logger.error(f"Error creating comment on issue #{issue_number}: {str(e)}")
            return None
    
    async def _create_pr_review_comment(self, pr_number: int, body: str) -> Optional[str]:
        """Post a review comment on a PR via GitHub API"""
        try:
            # Use issue comments endpoint (works for PRs too)
            url = f"{self.github_api_base}/repos/{self.github_repo}/issues/{pr_number}/comments"
            
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.post(
                    url,
                    headers=self._get_github_headers(),
                    json={"body": body}
                )
                response.raise_for_status()
                
                comment = response.json()
                comment_url = comment.get("html_url")
                logger.info(f"Posted review comment on PR #{pr_number}: {comment_url}")
                return comment_url
                
        except httpx.HTTPStatusError as e:
            logger.error(f"GitHub API error creating PR review comment #{pr_number}: {e.response.status_code}")
            return None
        except Exception as e:
            logger.error(f"Error creating PR review comment #{pr_number}: {str(e)}")
            return None
    
    # ========================================
    # Private Helper Methods - AI Analysis
    # ========================================
    
    async def _analyze_issue_with_ai(self, title: str, body: str) -> Optional[str]:
        """Call MCP /analyze endpoint for issue analysis"""
        try:
            system_message = """You are a technical project manager analyzing GitHub issues.

Analyze the issue and provide:
1. Issue Type (bug, feature, enhancement, documentation, question)
2. Priority Level (critical, high, medium, low)
3. Suggested Labels (comma-separated)
4. Brief Analysis (2-3 sentences)
5. Recommended Actions

Format your response clearly with sections."""

            prompt = f"""Title: {title}

Description:
{body if body else "No description provided"}

Analyze this GitHub issue and provide your assessment."""

            url = f"{self.mcp_server_url}/analyze"
            
            async with httpx.AsyncClient(timeout=60.0) as client:
                response = await client.post(
                    url,
                    json={
                        "prompt": prompt,
                        "system_message": system_message
                    }
                )
                response.raise_for_status()
                
                result = response.json()
                analysis = result.get("result", "")
                logger.info(f"AI analysis completed (tokens: {result.get('tokens', {}).get('total_tokens', 0)})")
                return analysis
                
        except httpx.HTTPStatusError as e:
            logger.error(f"MCP server error during issue analysis: {e.response.status_code}")
            return None
        except Exception as e:
            logger.error(f"Error analyzing issue with AI: {str(e)}")
            return None
    
    async def _review_pr_with_ai(
        self,
        title: str,
        description: str,
        files: List[Dict[str, Any]]
    ) -> Optional[str]:
        """Call MCP /analyze endpoint for PR review"""
        try:
            system_message = """You are an experienced code reviewer analyzing pull requests.

Review the PR and provide:
1. Overall Assessment (approve, request changes, comment)
2. Security Concerns (if any)
3. Code Quality Issues (if any)
4. Performance Considerations (if any)
5. Suggestions for Improvement
6. Positive Aspects

Be constructive and specific in your feedback."""

            # Build file summary
            files_summary = []
            for file in files[:10]:  # Limit to first 10 files
                files_summary.append(
                    f"- {file['filename']} (+{file.get('additions', 0)} -{file.get('deletions', 0)})"
                )
            
            files_text = "\n".join(files_summary)
            if len(files) > 10:
                files_text += f"\n... and {len(files) - 10} more files"

            prompt = f"""Title: {title}

Description:
{description if description else "No description provided"}

Changed Files:
{files_text}

Review this pull request and provide your assessment."""

            url = f"{self.mcp_server_url}/analyze"
            
            async with httpx.AsyncClient(timeout=60.0) as client:
                response = await client.post(
                    url,
                    json={
                        "prompt": prompt,
                        "system_message": system_message
                    }
                )
                response.raise_for_status()
                
                result = response.json()
                review = result.get("result", "")
                logger.info(f"AI review completed (tokens: {result.get('tokens', {}).get('total_tokens', 0)})")
                return review
                
        except httpx.HTTPStatusError as e:
            logger.error(f"MCP server error during PR review: {e.response.status_code}")
            return None
        except Exception as e:
            logger.error(f"Error reviewing PR with AI: {str(e)}")
            return None
    
    # ========================================
    # Utility Methods
    # ========================================
    
    def _parse_labels_from_analysis(self, analysis: str) -> List[str]:
        """Parse suggested labels from AI analysis text"""
        labels = []
        
        # Look for common label patterns in analysis
        analysis_lower = analysis.lower()
        
        # Issue type labels
        if "bug" in analysis_lower:
            labels.append("bug")
        if "feature" in analysis_lower or "enhancement" in analysis_lower:
            labels.append("enhancement")
        if "documentation" in analysis_lower or "docs" in analysis_lower:
            labels.append("documentation")
        if "question" in analysis_lower:
            labels.append("question")
        
        # Priority labels
        if "critical" in analysis_lower or "urgent" in analysis_lower:
            labels.append("priority: critical")
        elif "high priority" in analysis_lower:
            labels.append("priority: high")
        elif "low priority" in analysis_lower:
            labels.append("priority: low")
        
        # Security labels
        if "security" in analysis_lower:
            labels.append("security")
        
        # Remove duplicates
        return list(set(labels))
    
    def is_configured(self) -> bool:
        """Check if GitHub service is properly configured"""
        return bool(self.github_token and self.github_repo)
    
    # ========================================
    # Auto-Fix PR Creation
    # ========================================
    
    async def create_auto_fix_pr(self, issue_number: int) -> Dict[str, Any]:
        """
        Main method: Create auto-fix PR for an issue.
        
        Workflow:
        1. Fetch issue details
        2. Extract file path from issue title/body
        3. Get current file content from GitHub
        4. Generate fix with AI (providing full current code)
        5. Create new branch (fix-issue-{number})
        6. Commit changes
        7. Open pull request
        
        Args:
            issue_number: The issue number to fix
            
        Returns:
            Dict with success status, PR number, and PR URL
        """
        try:
            logger.info(f"Starting auto-fix PR creation for issue #{issue_number}")
            
            # Step 1: Fetch issue details
            issue = await self._get_issue(issue_number)
            if not issue:
                return {
                    "success": False,
                    "error": f"Issue #{issue_number} not found"
                }
            
            title = issue["title"]
            body = issue.get("body", "")
            
            # Step 2: Extract file path
            file_path = self._extract_file_path_from_issue(title, body)
            if not file_path:
                return {
                    "success": False,
                    "error": "Could not extract file path from issue"
                }
            
            logger.info(f"Extracted file path: {file_path}")
            
            # Step 3: Get repository info and default branch
            repo_info = await self._get_repository()
            if not repo_info:
                return {
                    "success": False,
                    "error": "Could not fetch repository information"
                }
            
            default_branch = repo_info.get("default_branch", "main")
            
            # Step 4: Get current file content
            file_data = await self._get_file_content(file_path, default_branch)
            if not file_data:
                return {
                    "success": False,
                    "error": f"Could not fetch file content for {file_path}"
                }
            
            current_code = file_data["content"]
            file_sha = file_data["sha"]
            
            logger.info(f"Fetched current file content ({len(current_code)} characters)")
            
            # Step 5: Generate fix with AI
            fix_result = await self._generate_code_fix(title, body, file_path, current_code)
            if not fix_result:
                return {
                    "success": False,
                    "error": "AI failed to generate fix"
                }
            
            fixed_code = fix_result["code"]
            explanation = fix_result["explanation"]
            
            logger.info(f"Generated fix with AI")
            
            # Step 6: Create new branch
            branch_name = f"fix-issue-{issue_number}"
            branch_created = await self._create_branch(branch_name, default_branch)
            if not branch_created:
                return {
                    "success": False,
                    "error": f"Could not create branch {branch_name}"
                }
            
            logger.info(f"Created branch: {branch_name}")
            
            # Step 7: Commit changes
            commit_message = f"Fix: {title}\n\nCloses #{issue_number}"
            file_updated = await self._update_file(
                file_path=file_path,
                content=fixed_code,
                message=commit_message,
                branch=branch_name,
                sha=file_sha
            )
            
            if not file_updated:
                return {
                    "success": False,
                    "error": "Could not commit changes to branch"
                }
            
            logger.info(f"Committed changes to {branch_name}")
            
            # Step 8: Create pull request
            pr_title = f"Auto-fix: {title}"
            pr_body = f"""## 🤖 Auto-Fix for Issue #{issue_number}

### Changes Made
{explanation}

### File Modified
- `{file_path}`

### AI Analysis
This fix was automatically generated using Azure OpenAI based on the issue description.

Closes #{issue_number}

---
*Generated by Zava AI Portal*
"""
            
            pr_result = await self._create_pull_request(
                title=pr_title,
                body=pr_body,
                head=branch_name,
                base=default_branch
            )
            
            if not pr_result:
                return {
                    "success": False,
                    "error": "Could not create pull request"
                }
            
            logger.info(f"Created PR #{pr_result['number']}: {pr_result['html_url']}")
            
            return {
                "success": True,
                "issue_number": issue_number,
                "pr_number": pr_result["number"],
                "pr_url": pr_result["html_url"],
                "branch": branch_name,
                "file_path": file_path,
                "explanation": explanation
            }
            
        except Exception as e:
            logger.error(f"Error creating auto-fix PR for issue #{issue_number}: {str(e)}")
            return {
                "success": False,
                "error": str(e)
            }
    
    def _extract_file_path_from_issue(self, title: str, body: str) -> Optional[str]:
        """
        Extract file path from issue title or body.
        
        Looks for patterns like:
        - "in app.py"
        - "file: config.py"
        - "`src/main.py`"
        - "in `frontend/app.js`"
        
        Args:
            title: Issue title
            body: Issue body
            
        Returns:
            File path or None if not found
        """
        text = f"{title} {body}"
        
        # Pattern 1: Backticks - `path/to/file.py`
        backtick_pattern = r'`([a-zA-Z0-9_/\-\.]+\.[a-zA-Z0-9]+)`'
        match = re.search(backtick_pattern, text)
        if match:
            return match.group(1)
        
        # Pattern 2: "in filename.ext"
        in_pattern = r'\bin\s+([a-zA-Z0-9_/\-\.]+\.[a-zA-Z0-9]+)'
        match = re.search(in_pattern, text, re.IGNORECASE)
        if match:
            return match.group(1)
        
        # Pattern 3: "file: filename.ext"
        file_pattern = r'file:\s*([a-zA-Z0-9_/\-\.]+\.[a-zA-Z0-9]+)'
        match = re.search(file_pattern, text, re.IGNORECASE)
        if match:
            return match.group(1)
        
        # Pattern 4: "path/to/file.ext" (without backticks)
        path_pattern = r'\b([a-zA-Z0-9_]+/[a-zA-Z0-9_/\-\.]+\.[a-zA-Z0-9]+)\b'
        match = re.search(path_pattern, text)
        if match:
            return match.group(1)
        
        logger.warning("Could not extract file path from issue")
        return None
    
    async def _generate_code_fix(
        self,
        title: str,
        body: str,
        file_path: str,
        current_code: str
    ) -> Optional[Dict[str, Any]]:
        """
        Generate code fix using AI.
        
        CRITICAL: Provides COMPLETE current file content to preserve all code.
        
        Args:
            title: Issue title
            body: Issue description
            file_path: Path to the file to fix
            current_code: COMPLETE current file content
            
        Returns:
            Dict with 'code' (complete fixed file) and 'explanation'
        """
        try:
            system_message = f"""You are an expert software engineer fixing a bug in {file_path}.

CRITICAL INSTRUCTIONS:
1. You will receive the COMPLETE current file content
2. You MUST return the COMPLETE file with ALL original code preserved
3. Make ONLY the specific changes needed to fix the issue
4. DO NOT truncate, omit, or use placeholders like "... rest of code ..."
5. Preserve all imports, functions, classes, and formatting
6. Return ONLY the complete fixed code, no explanations or markdown

The fixed code should be production-ready and complete."""

            prompt = f"""Issue: {title}

Description: {body}

COMPLETE CURRENT FILE CONTENT ({file_path}):
```
{current_code}
```

Generate the COMPLETE fixed file. Include ALL original code with ONLY the necessary changes to fix this issue.
Return ONLY the complete fixed code without any markdown formatting or explanations."""

            url = f"{self.mcp_server_url}/analyze"
            
            async with httpx.AsyncClient(timeout=120.0) as client:  # Longer timeout for code generation
                response = await client.post(
                    url,
                    json={
                        "prompt": prompt,
                        "system_message": system_message
                    }
                )
                response.raise_for_status()
                
                result = response.json()
                fixed_code = result.get("result", "")
                
                # Clean up code if wrapped in markdown
                if fixed_code.startswith("```"):
                    # Remove markdown code blocks
                    lines = fixed_code.split("\n")
                    if lines[0].startswith("```"):
                        lines = lines[1:]
                    if lines[-1].strip() == "```":
                        lines = lines[:-1]
                    fixed_code = "\n".join(lines)
                
                # Generate explanation separately
                explanation_prompt = f"In 2-3 sentences, explain what was changed in {file_path} to fix: {title}"
                explanation_response = await client.post(
                    url,
                    json={
                        "prompt": explanation_prompt,
                        "system_message": "You are a technical writer explaining code changes concisely."
                    }
                )
                explanation = explanation_response.json().get("result", "Code has been fixed.")
                
                logger.info(f"Generated code fix (tokens: {result.get('tokens', {}).get('total_tokens', 0)})")
                
                return {
                    "code": fixed_code.strip(),
                    "explanation": explanation.strip()
                }
                
        except Exception as e:
            logger.error(f"Error generating code fix: {str(e)}")
            return None
    
    async def _get_repository(self) -> Optional[Dict[str, Any]]:
        """Get repository information including default branch"""
        try:
            url = f"{self.github_api_base}/repos/{self.github_repo}"
            
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.get(url, headers=self._get_github_headers())
                response.raise_for_status()
                
                repo = response.json()
                logger.info(f"Fetched repository info: default branch = {repo.get('default_branch')}")
                return repo
                
        except Exception as e:
            logger.error(f"Error fetching repository info: {str(e)}")
            return None
    
    async def _get_file_content(self, file_path: str, branch: str) -> Optional[Dict[str, Any]]:
        """
        Fetch file content from GitHub repository.
        
        Args:
            file_path: Path to file in repository
            branch: Branch name
            
        Returns:
            Dict with 'content' (decoded string) and 'sha' (for updates)
        """
        try:
            url = f"{self.github_api_base}/repos/{self.github_repo}/contents/{file_path}"
            params = {"ref": branch}
            
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.get(url, headers=self._get_github_headers(), params=params)
                response.raise_for_status()
                
                file_data = response.json()
                
                # Decode base64 content
                content_b64 = file_data.get("content", "")
                content = base64.b64decode(content_b64).decode("utf-8")
                
                logger.info(f"Fetched file content: {file_path} ({len(content)} chars)")
                
                return {
                    "content": content,
                    "sha": file_data.get("sha")
                }
                
        except httpx.HTTPStatusError as e:
            logger.error(f"GitHub API error fetching file {file_path}: {e.response.status_code}")
            return None
        except Exception as e:
            logger.error(f"Error fetching file {file_path}: {str(e)}")
            return None
    
    async def _create_branch(self, branch_name: str, base_branch: str) -> bool:
        """
        Create a new branch from base branch.
        
        Args:
            branch_name: Name for new branch
            base_branch: Base branch to create from
            
        Returns:
            True if successful
        """
        try:
            # Get SHA of base branch
            ref_url = f"{self.github_api_base}/repos/{self.github_repo}/git/ref/heads/{base_branch}"
            
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.get(ref_url, headers=self._get_github_headers())
                response.raise_for_status()
                
                base_sha = response.json()["object"]["sha"]
                
                # Create new branch
                create_url = f"{self.github_api_base}/repos/{self.github_repo}/git/refs"
                create_data = {
                    "ref": f"refs/heads/{branch_name}",
                    "sha": base_sha
                }
                
                response = await client.post(
                    create_url,
                    headers=self._get_github_headers(),
                    json=create_data
                )
                response.raise_for_status()
                
                logger.info(f"Created branch: {branch_name} from {base_branch}")
                return True
                
        except httpx.HTTPStatusError as e:
            if e.response.status_code == 422:
                logger.warning(f"Branch {branch_name} already exists")
                return True  # Branch exists, proceed
            logger.error(f"GitHub API error creating branch: {e.response.status_code}")
            return False
        except Exception as e:
            logger.error(f"Error creating branch {branch_name}: {str(e)}")
            return False
    
    async def _update_file(
        self,
        file_path: str,
        content: str,
        message: str,
        branch: str,
        sha: str
    ) -> bool:
        """
        Update file content on a branch.
        
        Args:
            file_path: Path to file
            content: New file content
            message: Commit message
            branch: Branch name
            sha: Current file SHA (for update)
            
        Returns:
            True if successful
        """
        try:
            url = f"{self.github_api_base}/repos/{self.github_repo}/contents/{file_path}"
            
            # Encode content to base64
            content_b64 = base64.b64encode(content.encode("utf-8")).decode("utf-8")
            
            data = {
                "message": message,
                "content": content_b64,
                "branch": branch,
                "sha": sha
            }
            
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.put(
                    url,
                    headers=self._get_github_headers(),
                    json=data
                )
                response.raise_for_status()
                
                logger.info(f"Updated file {file_path} on branch {branch}")
                return True
                
        except httpx.HTTPStatusError as e:
            logger.error(f"GitHub API error updating file: {e.response.status_code} - {e.response.text}")
            return False
        except Exception as e:
            logger.error(f"Error updating file {file_path}: {str(e)}")
            return False
    
    async def _create_pull_request(
        self,
        title: str,
        body: str,
        head: str,
        base: str
    ) -> Optional[Dict[str, Any]]:
        """
        Create a pull request.
        
        Args:
            title: PR title
            body: PR description
            head: Source branch
            base: Target branch
            
        Returns:
            PR data with number and URL
        """
        try:
            url = f"{self.github_api_base}/repos/{self.github_repo}/pulls"
            
            data = {
                "title": title,
                "body": body,
                "head": head,
                "base": base
            }
            
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.post(
                    url,
                    headers=self._get_github_headers(),
                    json=data
                )
                response.raise_for_status()
                
                pr = response.json()
                logger.info(f"Created PR #{pr['number']}: {pr['html_url']}")
                
                return {
                    "number": pr["number"],
                    "html_url": pr["html_url"],
                    "url": pr["url"]
                }
                
        except httpx.HTTPStatusError as e:
            logger.error(f"GitHub API error creating PR: {e.response.status_code} - {e.response.text}")
            return None
        except Exception as e:
            logger.error(f"Error creating pull request: {str(e)}")
            return None
